# Site settings
#--------------
title: Electronics Club, IIT Bombay
header-img: assets/img/home-bg.jpg
logo: assets/ico/logo.png
email: eciitb@gmail.com
copyright_name: Electronics Club, IIT Bombay
description: The electronics enthusiasts of IITB
#twitter_username: SBootstrap
github_username:  elec-club-iitb
#facebook_username:  IronSummitMedia
#email_username:  your-email@yourdomain.com

# Build settings
markdown: kramdown
highlighter: rouge
syntaxtheme: friendly
paginate: 5
exclude: ["scripts", "README.md"]
gems: ['jekyll-paginate', 'jekyll-sass-converter']

# Configuration for url/path
baseurl:
url: http://elec-club-iitb.github.io

# Permalink
permalink: /blog/:year/:month/:title/

# Declaring tutorials collection
collections:
  tutorials:
    permalink: /tutorials/:path/
    output: true

# For comments sections
disqus:
    short_name: eciitb
    comment_count: true
    developer_mode: true
